[doc] Readme model
savushkin-r-d/PJS_Glase_cheeses pull request #21
Opened 2024-12-01 20:35 UTC by NogameNo-life

2024-12-02 04:56 UTC, idzm requested changes

2024-12-02 04:56 UTC, idzm commented on .github/workflows/build.yml
Надо убрать данный файл из запроса.

2024-12-02 04:56 UTC, idzm commented on .github/workflows/maven.yml
Надо убрать данный файл из запроса.

2024-12-05 06:47 UTC, idzm submitted a review, later dismissed

2024-12-05 11:11 UTC, kostomarovvv approved these changes

2024-12-05 11:43 UTC, kostomarovvv approved these changes

2024-12-17 14:03 UTC, idzm approved these changes

2024-12-17 14:03 UTC, merged